// @generated by tauri-specta from the Rust command signatures — do not edit by hand.
// Regenerate with a debug build (`npm run tauri dev`) or `cargo test export_bindings`. See src-tauri/src/lib.rs.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Open a product folder read-only and project it for the UI Shell.
	 *  No commits, no pushes, no locks — pure read path (Issue #2).
	 */
	openProduct: (path: string) => typedError<ProductView, string>(__TAURI_INVOKE("open_product", { path })),
	/**
	 *  Begin silently watching the product folder for settled saves (Issue #4) and watcher-side
	 *  Auto-Lock (Issue #42). Each settled save produces a new **Stand**, emitted as a `stand-created`
	 *  event; the first save to a lockable path auto-acquires its lock (closing the
	 *  Binär-Invarianten-Fenster before any checkpoint) and emits a `lock-acquired` event carrying the
	 *  product-relative path so the UI re-reads the LED signal. Replaces any previous watch. The user
	 *  is never prompted; no git vocabulary surfaces.
	 */
	startWatching: (path: string) => typedError<null, string>(__TAURI_INVOKE("start_watching", { path })),
	/**  Stop watching the current product folder, if any. */
	stopWatching: () => typedError<null, string>(__TAURI_INVOKE("stop_watching")),
	/**
	 *  Read the product's version tree for the dark "display" zone (Issue #8): Stände as nodes,
	 *  Revisionen marked, offloaded markers reserved. Pure read — the git/LFS facts are
	 *  collected then projected; no mutation.
	 */
	readVersionGraph: (path: string) => typedError<VersionGraph, string>(__TAURI_INVOKE("read_version_graph", { path })),
	/**
	 *  Promote a Stand to a **Revision** (Issue #8): persist the human `notes` into
	 *  `VERSION_NOTES.md` (the only place human text lives — E28) and durably label the version.
	 *  Returns the refreshed version tree so the UI updates in one round-trip.
	 */
	promoteRevision: (path: string, standId: string, version: string, notes: string) => typedError<VersionGraph, string>(__TAURI_INVOKE("promote_revision", { path, standId, version, notes })),
	/**
	 *  Toggle a Revision's **Art** between Prototyp and Freigabe (Issue #41, E42). Raising to
	 *  Freigabe write-protects the tag (E8); toggling back is the deliberate reversible
	 *  „Un-Release". A new Revision is Prototyp by default; this is the one act that releases
	 *  it. Returns the refreshed version tree so the UI updates in one round-trip.
	 * 
	 *  The dreistufige Freigabe-Gate block-check that will run on raising to Freigabe is a
	 *  separate slice (Issue #52); its seam lives in [`toggle_revision_freigabe`].
	 */
	toggleRevisionArt: (path: string, version: string) => typedError<VersionGraph, string>(__TAURI_INVOKE("toggle_revision_art", { path, version })),
	/**
	 *  **Als Ordner öffnen** (Issue #55, E27/E3 — Default-Knoten-Verb des Graph-Raums): materialisiert
	 *  den Stand `stand_id` als *separaten, schreibgeschützten* Ordner neben dem Produkt (ein detached
	 *  `git worktree`). Die Werkbank (Jetzt-Zustand) bleibt unberührt — ein Klick auf einen alten Knoten
	 *  bewegt sie nie still. Idempotent: ein schon materialisierter Ordner wird nur zurückgegeben. Die
	 *  UI übergibt den zurückgegebenen Pfad dem OS zum Öffnen.
	 */
	knotenAlsOrdner: (path: string, standId: string, label: string) => typedError<GeoeffneterOrdner, string>(__TAURI_INVOKE("knoten_als_ordner", { path, standId, label })),
	/**
	 *  **Von hier abzweigen** (Issue #55, E27/E8/E43): ein bewusster neuer Branch ab dem Stand
	 *  `stand_id`. Bevor die Werkbank bewegt wird, sichert das Werkzeug jede laufende Arbeit als
	 *  gewöhnlichen Stand (E8) — kein `stash`, nichts geht verloren —, dann `checkout -b`. Gibt den
	 *  frisch projizierten Versionsbaum zurück, damit die neue Linie sofort erscheint.
	 */
	knotenAbzweigen: (path: string, standId: string, branch: string) => typedError<VersionGraph, string>(__TAURI_INVOKE("knoten_abzweigen", { path, standId, branch })),
	/**
	 *  **Zurückwerfen** (Issue #55, E27 — destruktiv, hinter der schwarzen „Historie anfassen"-Gate,
	 *  nie der Default): springt auf den alten Stand `stand_id`, aber **sicher** — keine versteckte
	 *  `reset --hard`/`rebase`-Mechanik (E43). Es sichert erst die laufende Arbeit (E8), holt dann den
	 *  alten Inhalt in die Werkbank und schreibt ihn als **neuen, vorwärts gerichteten Stand** fest
	 *  („behalten, nie umschreiben", E9 — voll reversibel). Gibt den frischen Versionsbaum zurück.
	 */
	knotenZurueckwerfen: (path: string, standId: string) => typedError<VersionGraph, string>(__TAURI_INVOKE("knoten_zurueckwerfen", { path, standId })),
	/**
	 *  Read the product's manual „abgeleitet von" edges and their Stale-Warnungen (Issue #10).
	 *  Edges are opt-in: a product with no edge file has zero edges and no warnings (E40). Pure
	 *  read — the edges + artifact timestamps are gathered then judged by the pure core.
	 */
	readEdges: (path: string) => typedError<EdgeView, string>(__TAURI_INVOKE("read_edges", { path })),
	/**
	 *  Draw a manual „abgeleitet von" edge (`derived` „stammt aus" `source`) and persist it
	 *  (Issue #10). Returns the refreshed edge view (edges + Stale-Warnungen) so the UI updates
	 *  in one round-trip.
	 */
	addEdge: (path: string, derived: string, source: string) => typedError<EdgeView, string>(__TAURI_INVOKE("add_edge", { path, derived, source })),
	/**  Remove a manual edge and persist the result (Issue #10). Returns the refreshed edge view. */
	removeEdge: (path: string, derived: string, source: string) => typedError<EdgeView, string>(__TAURI_INVOKE("remove_edge", { path, derived, source })),
	/**
	 *  Einen **Baustein-Paar-Default-Vorschlag bestätigen** (Issue #56, E20): legt eine Kante mit
	 *  Herkunft `PaarDefault` zwischen `derived` und `source` an und persistiert sie. Vorschläge werden
	 *  nie automatisch angelegt — erst dieser Klick bestätigt sie. Gibt die frische Kantensicht zurück
	 *  (samt verbleibender Vorschläge und Stale-Warnungen).
	 */
	confirmPairEdgeCmd: (path: string, derived: string, source: string) => typedError<EdgeView, string>(__TAURI_INVOKE("confirm_pair_edge_cmd", { path, derived, source })),
	/**
	 *  Import a chosen folder as a product via the clean, non-destructive path (Issue #3, E38):
	 *  `git init` if needed (existing repo left as-is), write `.gitattributes` lockable markers
	 *  from the Mergeability Classifier, make the first commit, then project it for the shell.
	 */
	importProduct: (path: string) => typedError<ImportResult, string>(__TAURI_INVOKE("import_product", { path })),
	/**
	 *  Probe a folder and run the pure Import Gate (Issue #7, E38). No mutation: returns the one
	 *  decision (clean-init | migrate-behind-gate | refuse) plus the facts it rests on, so the UI
	 *  can explain the stakes before any history is touched.
	 */
	evaluateGate: (path: string) => typedError<GateReport, string>(__TAURI_INVOKE("evaluate_gate", { path })),
	/**
	 *  Run the destructive `git lfs migrate` history rewrite — only reachable after the user
	 *  crosses the "Historie anfassen" gate in the UI, and only honoured when the live repo still
	 *  decides `migrate-behind-gate` (re-checked server-side; a shared repo is always refused).
	 */
	migrateHistory: (path: string) => typedError<ImportResult, string>(__TAURI_INVOKE("migrate_history", { path })),
	/**
	 *  Auto-acquire a `git lfs lock` for a lockable artifact being opened/edited (Issue #6, E31).
	 *  Mergeable-text paths are a no-op (returns `false`); lockable paths get locked (`true`).
	 *  The path is product-relative with forward slashes.
	 */
	lockArtifact: (product: string, path: string) => typedError<boolean, string>(__TAURI_INVOKE("lock_artifact", { product, path })),
	/**
	 *  The Status Reader (Issue #6): read `git lfs locks` + worktree status purely once, then
	 *  derive the per-artifact LED status (green/grey/orange) for the given product-relative paths.
	 *  No second source of truth — every call reads git back (E37).
	 */
	readStatus: (product: string, paths: string[]) => typedError<ArtifactSignal_Serialize[], string>(__TAURI_INVOKE("read_status", { product, paths })),
	/**
	 *  The live "Belegte Bausteine" panel (Issue #6, E37): the locks held by anyone but us, read
	 *  purely from `git lfs locks`. No presence service.
	 */
	readForeignLocks: (product: string) => typedError<ForeignLock[], string>(__TAURI_INVOKE("read_foreign_locks", { product })),
	/**
	 *  Read the one-time **Einrichtungs-Zeremonie** state for a product (Issue #5, E41): is a
	 *  server connected, has the product been published, and the colleague's credential-free clone
	 *  URL. Pure read — the UI shows the ceremony only when not yet configured, a settled
	 *  "eingerichtet" readout otherwise. This ceremony is the rare, explicit exception where
	 *  git-near wording is allowed; the daily sync stays silent.
	 */
	readSetupState: (path: string) => typedError<SetupReport, string>(__TAURI_INVOKE("read_setup_state", { path })),
	/**
	 *  Connect the self-hosted Forgejo/Gitea server (Issue #5, E41; credential-free since ADR 0004 /
	 *  Issue #92). Draws everything server-related from the app-wide **Konto**: the Base-URL and the
	 *  owner-default (the Konto username) come from `konto::read_konto`, and the frontend supplies only
	 *  the optional `owner` (Besitzer/Team) + `repo` (Produkt-Name). Configures the git remote with the
	 *  credential-free clone URL and enables `locksverify`; writes **no** credentials (the Konto is the
	 *  sole writer of those, host-keyed in the OS keystore at Konto-save time). With **no Konto set** it
	 *  refuses with a clear typed `error` so the frontend points the user at the Konto panel instead of
	 *  asking for credentials. The returned report carries only the credential-free clone URL.
	 */
	connectServer: (path: string, owner: string, repo: string) => typedError<SetupReport, AppError>(__TAURI_INVOKE("connect_server", { path, owner, repo })),
	/**
	 *  Perform the **first push** that publishes the product to the connected server (Issue #5,
	 *  E41), setting the upstream so the later silent daily sync has a tracking ref. Returns the
	 *  refreshed ceremony state (now `eingerichtet`).
	 */
	publishToServer: (path: string, other: string | null) => typedError<PublishOutcome, AppError>(__TAURI_INVOKE("publish_to_server", { path, other })),
	/**
	 *  The Lock Warden checkpoint (Issue #9, E35): at a checkpoint for one artifact, read the world
	 *  (path kind, lock state, clean/dirty) purely once, let the safety-critical pure Warden decide
	 *  the single action — `freigabe-push` | `sicherungs-push` | `auto-unlock` | `refuse` — and carry
	 *  it out. `revision = true` is a Revision (Freigabe candidate); `false` is a laufender
	 *  Checkpoint (Sicherungs at most). The action taken is returned in the tool's own vocabulary,
	 *  never raw git. The Binär-Invariante lives in the pure core: a locked binary change is never
	 *  published while the lock is held.
	 */
	runCheckpoint: (product: string, path: string, revision: boolean) => typedError<WardenAction, string>(__TAURI_INVOKE("run_checkpoint", { product, path, revision })),
	/**
	 *  **Freigeben** (Issue #54-Folge): the explicit „ich bin fertig"-act of a Revision. Publishes
	 *  the whole current branch to the *actually shared* branch of the remote (Issue #64) and then
	 *  self-heals — auto-unlocks every held-clean binary now published ("unlock at push", E35). This
	 *  replaces the per-path Revision checkpoint for the publish: at revision time the work is
	 *  already committed, so the per-path Warden always saw a clean path and `Refuse`d, leaving the
	 *  branch never pushed to the shared stand. Returns `freigabe-push` so the readout lights
	 *  „freigegeben"; the per-path Warden stays unchanged for the silent laufend backup rhythm.
	 */
	freigeben: (product: string) => typedError<WardenAction, string>(__TAURI_INVOKE("freigeben", { product })),
	/**
	 *  **Sichern** (Issue #54): the visible, manual **Sicherungs-Push** — a personal backup of the
	 *  current branch into the personal namespace `refs/personal/<user>/<branch>` on the remote. This
	 *  is the explicit press of the toolbar's „Sichern"-Knopf: a private backup (incl. half-finished
	 *  binaries under an active lock) that, by construction of the ref, can **NEVER** reach the shared
	 *  `main`. It does not release any lock — backup yes, Freigabe no (E35). Returns `sicherungs-push`
	 *  so the Sicherungsstatus readout lights „gesichert". Distinct from the silent laufend rhythm: the
	 *  daily Auto-Commit stays quiet; this is the user's deliberate, visible backup gesture.
	 */
	sichern: (product: string) => typedError<WardenAction, string>(__TAURI_INVOKE("sichern", { product })),
	/**
	 *  Die **Freigabe-Gate**-Verdict für einen Checkpoint bei der angestrebten Revision-Art
	 *  berechnen (Issue #52, E19/E19.3). Sammelt die offenen Punkte — offene Aufgaben (#49), Waisen
	 *  (#47) und Stale-Kanten (#10) — und staffelt sie **nach Härte** hinter **einem** kontextabhängigen
	 *  Knopf: alles sauber → „Taggen"; weicher Block (Waise/Pflicht) → „Trotzdem freigeben" + ein
	 *  protokollierter Satz; harter Block (offene blockierende Aufgabe) → Knopf aus, daneben die
	 *  Aufgabe mit ihren Auswegen. Reine Lesepfade der `_plm`-Stores; das Urteil ist der reine
	 *  [`freigabegate::decide_gate`]-Kern. Ein leeres Produkt ist sauber (sperrt nie aus — E22).
	 */
	evaluateFreigabeGate: (path: string, art: RevisionArt) => typedError<GateVerdict, string>(__TAURI_INVOKE("evaluate_freigabe_gate", { path, art })),
	/**
	 *  Den **protokollierten Begründungs-Satz** eines weichen Blocks festhalten (Issue #52, E19/§22.1).
	 *  Ein weicher Block (Waise / fehlendes Pflicht-Artefakt) ist bewusst überwindbar — aber **nur per
	 *  protokollierter Begründung**. Diese landet als dauerhafte Zeile im Diagnose-Log, damit das
	 *  „Trotzdem freigeben" nachvollziehbar bleibt.
	 */
	logFreigabeBegruendung: (version: string, begruendung: string) => __TAURI_INVOKE<void>("log_freigabe_begruendung", { version, begruendung }),
	/**
	 *  Das Git-/Sync-Diagnose-Log lesen (Issue #54-Folge) — das In-App-Diagnose-Panel pollt das, um
	 *  zu zeigen, **ob und warum** ein Push lief oder nicht (Warden-Entscheidung + reale git-Exits).
	 *  Älteste Zeile zuerst, jüngste zuletzt.
	 */
	readGitLog: () => __TAURI_INVOKE<string[]>("read_git_log"),
	/**  Den In-Memory-Ring des Diagnose-Logs leeren (die Logdatei bleibt als dauerhaftes Protokoll). */
	clearGitLog: () => __TAURI_INVOKE<void>("clear_git_log"),
	/**  Der absolute Pfad der Diagnose-Logdatei, damit das Panel „`tail -f <pfad>`" anbieten kann. */
	gitLogPath: () => __TAURI_INVOKE<string | null>("git_log_path"),
	/**
	 *  Die Etiketten des Produkt-Repos für den Picker im Melde-Formular lesen (Issue #85). Adresse +
	 *  Zugangsdaten wie bei `melde_problem` aus Remote + Konto. Off the main thread (Keystore + Netz).
	 */
	produktEtiketten: (path: string) => typedError<Label[], AppError>(__TAURI_INVOKE("produkt_etiketten", { path })),
	/**
	 *  **Ein Problem aus der laufenden Werkbank melden** (Issue #85): legt im Repository des gerade
	 *  geöffneten Produkts ein Forgejo/Gitea-Issue an — Titel + Beschreibung, getragt mit dem
	 *  Laufzeit-Etikett (`feedback::RUNTIME_LABEL_NAME`) plus den im Formular gewählten `labels`,
	 *  optional mit angehängtem Diagnose-Log (`log_anhaengen`). Adresse + Besitzer/Repo kommen aus der
	 *  `origin`-Remote des Produkts; authentifiziert mit den Konto-Zugangsdaten (host-keyed im
	 *  OS-Keystore — derselbe Pfad wie Push/Locks). Der Token wird nie ans Frontend gegeben oder
	 *  geloggt. Typisierte Fehler wie die Zeremonie-Commands: `auth` öffnet das Token-Feld, `keystore`
	 *  meldet den unerreichbaren Schlüsselbund, `error` ist alles übrige.
	 */
	meldeProblem: (path: string, titel: string, beschreibung: string, logAnhaengen: boolean, labels: number[]) => typedError<IssueRef, AppError>(__TAURI_INVOKE("melde_problem", { path, titel, beschreibung, logAnhaengen, labels })),
	/**
	 *  At a checkpoint, **auto-unlock every held lock whose path is locally clean** (Issue #42,
	 *  E31/E35 self-healing). Reuses the pure Lock Warden decision per held lock — the lock policy is
	 *  decided in one place, never duplicated. Returns the product-relative paths that were freed so
	 *  the UI can re-read the LED signals; a freed binary rests read-only (frei) again. Best-effort:
	 *  an LFS/network hiccup must never break the silent rhythm.
	 */
	sweepCleanLocks: (product: string) => typedError<string[], string>(__TAURI_INVOKE("sweep_clean_locks", { product })),
	/**
	 *  Run one **silent daily sync pass** (Issue #11, E41): fetch the remote stand, let the pure
	 *  Sync Decider judge the divergence, and carry out the result. Free, mergeable divergence is
	 *  merged silently with NO prompt (status `gesichert`); a contradiction over an unmergeable file
	 *  (binary OR KiCad nominal-text — the #3 buckets) STOPS the sync without merging and returns the
	 *  single **laute Ausnahme** — a domain-language question ("dein und X' Gehäuse-Stand
	 *  widersprechen sich — welcher gilt?"), never a git conflict marker. The daily vocabulary is
	 *  "aktuell / X arbeitet an Y / gesichert"; raw git (push/pull/merge) never surfaces.
	 */
	syncProduct: (path: string, other: string | null) => typedError<SyncOutcome, string>(__TAURI_INVOKE("sync_product", { path, other })),
	/**
	 *  List the local Bibliothek (Issue #39, ADR 0003): the seeded + user-added Bausteine and the
	 *  available Toolstacks. Pure read; missing/corrupt entries degrade to an empty list.
	 */
	listBibliothek: () => typedError<BibliothekView, string>(__TAURI_INVOKE("list_bibliothek")),
	/**
	 *  List the available standard Toolstacks from the Bibliothek (Issue #39). Convenience read for
	 *  the „Standard-Toolstack wählen"-Schritt der Produkt-Anlage (#50).
	 */
	listToolstacks: () => typedError<Toolstack[], string>(__TAURI_INVOKE("list_toolstacks")),
	/**
	 *  Resolve a named Toolstack from the Bibliothek to its ordered Baustein-`id`s (Issue #39).
	 *  Returns an error if the Toolstack is unknown. Used to seed a product stack from a chosen stack.
	 */
	toolstackBausteinIds: (toolstackId: string) => typedError<string[], string>(__TAURI_INVOKE("toolstack_baustein_ids", { toolstackId })),
	/**
	 *  Create/configure a product's Produkt-Stack as a **full self-contained copy** of the chosen
	 *  Bibliothek Bausteine, written to `_plm/stack.json` with a provenance stamp (Issue #39, ADR
	 *  0003). No live link to the Bibliothek — a later Bibliothek edit never reaches this product
	 *  (anti-drift). `toolstack` is the optional display name of the chosen standard stack. The
	 *  product-creation UI is #50; this is the backend the ceremony calls.
	 */
	createProductStackCmd: (product: string, bausteinIds: string[], toolstack: string | null) => typedError<ProduktStack_Serialize, string>(__TAURI_INVOKE("create_product_stack_cmd", { product, bausteinIds, toolstack })),
	/**
	 *  Extend an existing Produkt-Stack **additively** with further Bibliothek Bausteine (Issue #50,
	 *  „Tool erweitern" / „später ergänzen"). Already-copied Bausteine are kept verbatim — never re-pulled
	 *  from the Bibliothek (anti-drift: no silent version bump); only genuinely new `id`s are appended as
	 *  full copies. The newly onboarded Bausteine get their Tag-1 marker blocks written too (idempotent,
	 *  Issue #48). Returns the extended stack.
	 */
	extendProductStackCmd: (product: string, bausteinIds: string[]) => typedError<ProduktStack_Serialize, string>(__TAURI_INVOKE("extend_product_stack_cmd", { product, bausteinIds })),
	/**
	 *  Einen Baustein eines Produkts **stilllegen** bzw. reaktivieren (Issue #51, E17). Label-only und
	 *  (fast) umkehrbar: setzt nur den `stillgelegt`-Schalter in `_plm/stack.json`. Die alten Globs
	 *  hören dadurch auf zu greifen → ihre Dateien werden zu **Waisen** im Unzugeordnet-Fach; die
	 *  Ignore-/LFS-Marker-Blöcke bleiben als **Sediment** unangetastet in den Dotfiles liegen; **nichts
	 *  wird verschoben oder gelöscht**. Gibt die Wirkung + den neuen Stack + die frisch gefaltete
	 *  Werkbank zurück. Eine unbekannte `id` ist eine no-op (kein Fehler).
	 */
	stilllegenBausteinCmd: (product: string, bausteinId: string, stillgelegt: boolean) => typedError<StilllegenResult_Serialize, string>(__TAURI_INVOKE("stilllegen_baustein_cmd", { product, bausteinId, stillgelegt })),
	/**
	 *  Read a product's copied Produkt-Stack from `_plm/stack.json` (Issue #39). Pure read; a product
	 *  with no stack file reads as an empty stack (never an error). This is the anti-drift copy — it
	 *  reflects only what was copied in, never the live Bibliothek.
	 */
	readProductStack: (product: string) => typedError<ProduktStack_Serialize, string>(__TAURI_INVOKE("read_product_stack", { product })),
	/**
	 *  Read the product's **Werkbank** (Issue #47): turn tracked files into Artefakt-Karten by
	 *  convention via the pure Pattern-Zuordnung core, and gather the unlabeled tracked files into an
	 *  **Unzugeordnet-Fach pro Arbeitsbereich**. Each card carries its Hauptdatei (highest glob
	 *  priority) and a derived primary action (open the dominant file, else the folder) with an absolute
	 *  target so the UI can open it via the OS default program. Pure read — `git ls-files` is collected
	 *  once, then the pure core folds it; no mutation. A product without a Produkt-Stack has no
	 *  Glob-Satz, so every tracked file becomes a Waise (nothing is ever lost) rather than an error.
	 */
	readWerkbankCmd: (product: string) => typedError<WerkbankView, string>(__TAURI_INVOKE("read_werkbank_cmd", { product })),
	/**
	 *  **Manuelle Zuordnung** einer Waise zu einem Baustein (Folge von Issue #47/#50): der Nutzer
	 *  ordnet eine erfasste Datei aus der Software heraus einem Baustein zu — ohne sie im Dateimanager
	 *  zu verschieben. Die Zuordnung ist ein zerstörungsfreies Etikett in `_plm/zuordnung.json`; sie
	 *  gewinnt über die Glob/Heimat-Konvention und ignoriert die Heimat-Grenze. Gibt die frisch
	 *  berechnete Werkbank zurück, sodass die Karte sofort erscheint.
	 */
	assignArtefaktCmd: (product: string, file: string, bausteinId: string) => typedError<WerkbankView, string>(__TAURI_INVOKE("assign_artefakt_cmd", { product, file, bausteinId })),
	/**
	 *  Die **manuelle Zuordnung** einer Datei wieder lösen (Folge von Issue #47/#50): die Datei fällt
	 *  zurück auf die Konvention bzw. wird wieder zur Waise. Gibt die frisch berechnete Werkbank zurück.
	 */
	clearArtefaktCmd: (product: string, file: string) => typedError<WerkbankView, string>(__TAURI_INVOKE("clear_artefakt_cmd", { product, file })),
	/**
	 *  **Resolve the laute Ausnahme** (Issue #43, E41): the single moment the user answers the loud
	 *  question by choosing whose stand applies for the contested artifact. The backend then finishes
	 *  the sync with the chosen side and a raw git conflict marker is NEVER written to the worktree —
	 *  the dangerous hand-resolution stays hidden behind "mein Stand" / "Bens Stand". On success the
	 *  daily rhythm resumes quietly (`gesichert`); raw git (push/pull/merge) never surfaces.
	 */
	resolveSyncCmd: (path: string, artifact: string, choice: StandChoice) => typedError<SyncOutcome, string>(__TAURI_INVOKE("resolve_sync_cmd", { path, artifact, choice })),
	/**
	 *  List the registered products (Issue #45). Path-only: each entry is a folder path plus its
	 *  derived display name — no content is cached. A missing/corrupt registry reads as empty.
	 */
	listProducts: () => typedError<RegisteredProduct[], string>(__TAURI_INVOKE("list_products")),
	/**
	 *  Register a product folder into the app-level Produkt-Registry (Issue #45). Stores ONLY the
	 *  path (de-duplicated, normalized); the content is never copied. Returns the refreshed list.
	 */
	registerProduct: (path: string) => typedError<RegisteredProduct[], string>(__TAURI_INVOKE("register_product", { path })),
	/**
	 *  Remove a product from the Produkt-Registry (Issue #45). Drops only the registry entry; the
	 *  product folder on disk is never touched. Returns the refreshed list.
	 */
	unregisterProduct: (path: string) => typedError<RegisteredProduct[], string>(__TAURI_INVOKE("unregister_product", { path })),
	/**
	 *  Re-link a moved product (Issue #89, PRD-US5): a product whose folder was moved/renamed outside
	 *  the app points its registry entry at nothing and surfaces as offline. Rather than orphaning it,
	 *  the user re-points the entry to the new folder. The new path is validated as a plausible
	 *  product first ([`check_plausible_product`]) so there is no dead re-link; then the registry entry
	 *  is **replaced** (not duplicated) via the pure [`relink_path`](registry::relink_path) core — same
	 *  normalize/de-dup as registering, so re-linking onto an already-registered product merges instead
	 *  of duplicating. The display name is re-derived from the new path. Returns the refreshed list.
	 */
	relinkProduct: (oldPath: string, newPath: string) => typedError<RegisteredProduct[], string>(__TAURI_INVOKE("relink_product", { oldPath, newPath })),
	/**
	 *  Read the app-wide Konto (ADR 0004, Issue #90): returns the normalized Base-URL + the angemeldete
	 *  account, or `None` when no Konto is set yet. **Never** returns the token — it stays in the OS
	 *  keystore and never leaves the backend. A missing/corrupt config reads as "kein Konto" (`None`),
	 *  never an error.
	 */
	readKonto: () => typedError<{
	/**  Die normalisierte Server-Base-URL `scheme://host[:port]`. */
	base_url: string,
	/**  Der angemeldete Account-Name (aus `GET /api/v1/user`, beim Speichern bestätigt). */
	account: string,
} | null, string>(__TAURI_INVOKE("read_konto")),
	/**
	 *  Set up + verify the app-wide Konto (ADR 0004, Issue #90): normalize the typed Server-Adresse,
	 *  verify the credentials against `GET /api/v1/user` (200 = connection ok + token valid + returns
	 *  the account name; 401 = token wrong; network error = check server address), then persist the
	 *  Base-URL app-level and write the credentials to the OS keystore (host-keyed, like the existing
	 *  ceremony). Returns the Konto view (Base-URL + account) — **never** the token, which is never
	 *  echoed back or logged. Errors are typed like the existing ceremony commands: `auth` reopens the
	 *  token field, `keystore` reports the OS keystore is unreachable, `error` is everything else.
	 * 
	 *  The check deliberately covers ONLY connection + token validity — the repo-create permission is
	 *  NOT pre-checked (it surfaces honestly on first publish via `forgejo::ensure_repo`'s 403).
	 */
	saveKonto: (server: string, username: string, token: string) => typedError<KontoView, AppError>(__TAURI_INVOKE("save_konto", { server, username, token })),
	/**
	 *  **Konto entfernen** (ADR 0004, Issue #91): read the persisted Base-URL, delete the host-keyed
	 *  keystore entries for that Konto host, and remove the persisted Base-URL JSON. **Idempotent**: a
	 *  missing keystore entry and a missing JSON file are both success, so „entfernen" without a Konto
	 *  is a no-op, never an error (Kriterium 1 + 5).
	 * 
	 *  CRITICAL INVARIANT (ADR 0004): this NEVER touches existing product remotes — no `.git/config`
	 *  rewriting, no mass-repoint. Removing the Konto only pauses *sharing*; local work on products
	 *  continues unchanged, and a product re-shares once a Konto is set again.
	 */
	clearKonto: () => typedError<null, string>(__TAURI_INVOKE("clear_konto")),
	/**
	 *  The produktübergreifende Live-Suche (Issue #45, E45): a live Fan-out over the registry —
	 *  opens each reachable product and greps live over Dateinamen, `_plm` and `VERSION_NOTES.md`.
	 *  No central index, no mirror. Unreachable products are reported honestly in the result's
	 *  `offline` list with searched/total counts — never silently dropped.
	 */
	searchProducts: (query: string) => typedError<SearchResult, string>(__TAURI_INVOKE("search_products", { query })),
	/**
	 *  Read the product's Aufgaben & Hinweise (Issue #40). Tasks are opt-in: a product with no task
	 *  file has zero tasks — never an error. Pure read; the list is returned as-is, the UI splits it
	 *  into Aufgaben (block-capable) and Hinweise (never block) by `kind`.
	 */
	listTasks: (path: string) => typedError<Task[], string>(__TAURI_INVOKE("list_tasks", { path })),
	/**
	 *  Create an Aufgabe or Hinweis and persist it (Issue #40). The store mints the id + creation
	 *  timestamp; the minimal model (Titel/Typ/Verknüpfung/Fälligkeit + „blockiert überall") comes
	 *  from the caller. Returns the refreshed list so the UI updates in one round-trip.
	 */
	createTaskCmd: (path: string, title: string, kind: TaskKind, link: 
/**  The product as a whole. */
{ kind: "produkt" } | 
/**  A specific Version/Revision, by its human label or Stand id. */
{ kind: "version"; ref: string } | 
/**  An Arbeitsbereich, by its product-relative path. */
{ kind: "arbeitsbereich"; ref: string } | 
/**  A single Artefakt, by its product-relative path. */
{ kind: "artefakt"; ref: string } | null, due: string | null, blocksEverywhere: boolean) => typedError<Task[], string>(__TAURI_INVOKE("create_task_cmd", { path, title, kind, link, due, blocksEverywhere })),
	/**
	 *  Edit one task (Issue #40). The UI edit form carries a task's full state, so this command
	 *  **replaces** title/kind/link/due/flag with the given values (a `null` `link`/`due` clears the
	 *  Verknüpfung/Fälligkeit). `status` is left untouched here — it has its own command. (The pure
	 *  [`TaskEdit`] keeps the finer clear-vs-untouched distinction for internal use; the wire stays
	 *  JSON-honest by always setting these fields.) Returns the refreshed list.
	 */
	editTaskCmd: (path: string, id: string, title: string, kind: TaskKind, link: 
/**  The product as a whole. */
{ kind: "produkt" } | 
/**  A specific Version/Revision, by its human label or Stand id. */
{ kind: "version"; ref: string } | 
/**  An Arbeitsbereich, by its product-relative path. */
{ kind: "arbeitsbereich"; ref: string } | 
/**  A single Artefakt, by its product-relative path. */
{ kind: "artefakt"; ref: string } | null, due: string | null, blocksEverywhere: boolean) => typedError<Task[], string>(__TAURI_INVOKE("edit_task_cmd", { path, id, title, kind, link, due, blocksEverywhere })),
	/**
	 *  Set just the status of one task — erledigen / verwerfen / wieder öffnen (Issue #40). The
	 *  common gesture, kept separate from the full edit. Returns the refreshed list.
	 */
	setTaskStatusCmd: (path: string, id: string, status: TaskStatus) => typedError<Task[], string>(__TAURI_INVOKE("set_task_status_cmd", { path, id, status })),
	/**  Delete one task (Issue #40). Absent id ⇒ no-op. Returns the refreshed list. */
	deleteTaskCmd: (path: string, id: string) => typedError<Task[], string>(__TAURI_INVOKE("delete_task_cmd", { path, id })),
	/**
	 *  Decide whether a checkpoint at the intended Revision-Art is blocked by open Aufgaben
	 *  (Issue #49, E42). The Strenge lives on the Art: a Freigabe is blocked by any open Aufgabe, a
	 *  Prototyp only by an open „blockiert überall" Aufgabe, and a Hinweis never blocks. Pure read of
	 *  the product's task store; the judgement is the pure [`aufgabenblock::decide_block`] core.
	 *  Returns whether it is blocked and the ids of the blocking tasks (so Issue #52's Freigabe-Gate
	 *  can name them). A product with no task store is never blocked.
	 */
	evaluateTaskBlock: (path: string, art: RevisionArt) => typedError<BlockDecision, string>(__TAURI_INVOKE("evaluate_task_block", { path, art })),
};

/* Types */
/**
 *  A typed error for the auth-bearing ceremony commands (Issue #22). The `code` lets the frontend
 *  react precisely — `"auth"` reopens the credential field, `"keystore"` reports the OS keystore is
 *  unreachable — while `message` carries the human German text. Serialised to the frontend as
 *  `{ code, message }`.
 */
export type AppError = {
	code: string,
	message: string,
};

/**  Eine **Artefakt-Karte** auf der Werkbank: per Konvention aus erfassten Dateien gebildet. */
export type ArtefaktKarte = {
	/**  Stabiler Schlüssel `"<baustein-id>:<ordner>"` — die UI keyt Karten darauf. */
	artefakt_id: string,
	/**  Menschlicher Baustein-Name (z.B. „KiCad"), trägt das Karten-Label. */
	baustein: string,
	/**  Ordner des Artefakts relativ zur Produktwurzel (Vorwärts-Slashes), die Heimat-Spur. */
	ordner: string,
	/**
	 *  Die **Hauptdatei** (höchste Glob-Priorität), produkt-relativ; `None` falls keine
	 *  (degeneriert — eine Karte hat normalerweise immer mindestens eine Datei).
	 */
	hauptdatei: string | null,
	/**  Alle erfassten Dateien dieses Artefakts, produkt-relativ, sortiert. */
	dateien: string[],
	/**  Die **abgeleitete primäre Aktion** des Ein-Klick-Öffnens (Datei vs. Ordner, PRD §14). */
	primaer: PrimaerAktion,
	/**
	 *  Das Ziel der primären Aktion, **absolut** auf der Platte (Datei- oder Ordnerpfad), damit
	 *  die UI es direkt im OS-Standardprogramm öffnen kann. `None` nur im degenerierten Fall.
	 */
	ziel: string | null,
	/**
	 *  Der **abgeleitete Karten-Status** + Stale-Flag (Issue #53, E26): live aus Git (Status)
	 *  und Kanten (Stale) berechnet, nie gespeichert. Vom Falten zunächst auf den ruhigen
	 *  Default gesetzt; die Glue [`read_werkbank`] füllt ihn aus echten Git-/Kanten-Fakten.
	 */
	projektion: KartenProjektion,
};

/**
 *  What the UI needs to render one artifact's LED: the derived status plus, when foreign-
 *  locked, who holds it and since when (for the "gesperrt von X seit …" tooltip).
 */
export type ArtifactSignal = ArtifactSignal_Serialize | ArtifactSignal_Deserialize;

/**
 *  What the UI needs to render one artifact's LED: the derived status plus, when foreign-
 *  locked, who holds it and since when (for the "gesperrt von X seit …" tooltip).
 */
export type ArtifactSignal_Deserialize = {
	/**  Product-relative artifact path the signal is for. */
	path: string,
	status: ArtifactStatus,
	/**  Foreign lock owner, present iff `status == LockedByOther`. */
	locked_by: string | null,
	/**  Foreign lock timestamp, present iff `status == LockedByOther`. */
	locked_at: string | null,
	/**  Ready-to-show tooltip, "gesperrt von X seit …", present iff foreign-locked. */
	tooltip: string | null,
};

/**
 *  What the UI needs to render one artifact's LED: the derived status plus, when foreign-
 *  locked, who holds it and since when (for the "gesperrt von X seit …" tooltip).
 */
export type ArtifactSignal_Serialize = {
	/**  Product-relative artifact path the signal is for. */
	path: string,
	status: ArtifactStatus,
	/**  Foreign lock owner, present iff `status == LockedByOther`. */
	locked_by?: string | null,
	/**  Foreign lock timestamp, present iff `status == LockedByOther`. */
	locked_at?: string | null,
	/**  Ready-to-show tooltip, "gesperrt von X seit …", present iff foreign-locked. */
	tooltip?: string | null,
};

/**
 *  The derived status of one artifact — the direct translation of the lock signals into the
 *  LED colours from the Stilbeschreibung (§ Status-Punkt). Nothing here is stored; it is
 *  recomputed from a [`StatusSnapshot`] every time (E37).
 */
export type ArtifactStatus = 
/**  Free / clean, no lock anywhere → **green** LED (`--led-free`). */
"free" | 
/**
 *  In progress / ruhend: locked **by us**, or just locally dirty → **grey** LED
 *  (`--led-working`). The quiet everyday state.
 */
"in-progress" | 
/**
 *  Locked **by someone else** → needs attention → **orange** LED (`--led-attention`),
 *  tooltip "gesperrt von X seit …". The single loud exception.
 */
"locked-by-other";

/**
 *  Art einer Startaufgabe: eine **Aufgabe** kann blockieren (verpflichtend), ein **Hinweis**
 *  blockiert nie (PRD §27). Die Trennung läuft über die Blockier-Fähigkeit, nicht die Wichtigkeit.
 */
export type AufgabenTyp = 
/**  Verpflichtend; *kann* blockieren (siehe `blockiert`). */
"aufgabe" | 
/**  Blockiert nie. */
"hinweis";

/**  Ein **Baustein**: das wiederverwendbare Tool-Wissen für ein Tool (ADR 0003). */
export type Baustein = {
	/**  Stabile Kebab-Identität, z.B. `"kicad"`. Eindeutig in der Bibliothek. */
	id: string,
	/**  Monotone Ganzzahl-Version; höher = neuer. Trägt das version-gegatete Seeding (ADR 0003). */
	version: number,
	/**  Menschlicher Name, z.B. `"KiCad"`. */
	name: string,
	/**  Default-Heimat-Ordner (Arbeitsbereich), z.B. `"elektronik"`. Pro Produkt auflösbar. */
	heimat: string,
	/**  Artefakt-Globs, **geordnet**: `[0]` ist die Hauptdatei-Regel (höchste Priorität). */
	globs: string[],
	/**  Ignore-Presets (Marker-Block-Zeilen für `.gitignore`). */
	ignore?: string[],
	/**  LFS-Muster (Marker-Block-Zeilen für `.gitattributes`). */
	lfs?: string[],
	/**  Öffnen-Aktion der Artefakt-Karte. */
	oeffnen?: Oeffnen,
	/**  Beim Onboarding anzulegende Startaufgaben/Hinweise. */
	startaufgaben?: Startaufgabe[],
	/**  Interne Default-Kanten (pattern-basiert) — Baustein-Default (E20), beim Onboarding angelegt. */
	default_kanten?: DefaultKante[],
	/**  Paar-Default-Kanten (E20): Vorschläge, sobald ein Partner-Baustein mit im Stack liegt. */
	paar_default_kanten?: PaarDefaultKante[],
	/**  Label-only stillgelegt (PRD §10): alte Globs greifen nicht mehr, nichts wird gelöscht. */
	stillgelegt?: boolean,
};

/**  The Bibliothek as sent to the UI: the available Bausteine and Toolstacks. */
export type BibliothekView = {
	bausteine: Baustein[],
	toolstacks: Toolstack[],
};

/**
 *  The single decision the Aufgaben-Block core returns for a checkpoint. Exactly one; total. It
 *  carries the **ids of the blocking tasks** so the UI can name them („Freigabe blockiert durch
 *  N offene Aufgaben") without re-running the rule.
 */
export type BlockDecision = {
	/**
	 *  Whether the checkpoint is blocked at all. `true` iff [`BlockDecision::blocking_task_ids`]
	 *  is non-empty (kept as an explicit, serialized field so the UI reads one honest flag).
	 */
	blocked: boolean,
	/**
	 *  The ids of the open Aufgaben that block this checkpoint, in input order. Empty ⇔ not
	 *  blocked. Exactly the tasks for which [`task_blocks_at`] held.
	 */
	"blocking-task-ids": string[],
};

/**
 *  Eine interne Default-Kante des Bausteins: ein abgeleitetes Glob „stammt aus" einem Quell-Glob
 *  (z.B. Fertigungs-STL stammt aus der CAD-Quelle). Pattern-basiert, nicht pro-Datei (PRD §13).
 *  **Baustein-Default** (E20): kommt beim Onboarding automatisch, ganz **innerhalb** des Bausteins.
 */
export type DefaultKante = {
	/**  Glob des abgeleiteten Artefakts. */
	derived_glob: string,
	/**  Glob der Quelle, aus der es stammt. */
	source_glob: string,
};

/**
 *  A manual „abgeleitet von" edge: `derived` „stammt aus" `source`. Both are product-relative
 *  artifact paths (the same identity the [`crate::projection::Baustein`] `path` carries).
 * 
 *  Die `herkunft` trägt die Herkunftsstufe (E20). Alte `kanten.json` ohne das Feld lesen sich als
 *  [`KantenHerkunft::Hand`] (serde-Default) — die Stale-Logik ist davon **unberührt**.
 */
export type Edge = {
	/**  The derivation — the artifact that was made *from* `source`. */
	derived: string,
	/**  The source the derivation „stammt aus". */
	source: string,
	/**  Herkunftsstufe (E20). Fehlt sie auf der Platte, gilt `Hand` (Altbestand/Hand-Kante). */
	herkunft?: KantenHerkunft,
};

/**
 *  The edge set plus its computed Stale-Warnungen, returned to the UI in one round-trip. Trägt seit
 *  #56 zusätzlich die offenen **Paar-Default-Vorschläge** (deterministisch, per Klick bestätigt).
 */
export type EdgeView = {
	edges: Edge[],
	warnings: StaleWarning[],
	/**
	 *  Offene Baustein-Paar-Default-Vorschläge (E20): noch nicht bestätigte Kanten. Leer, wenn keine
	 *  passende Baustein-Paarung im Stack liegt oder alle bereits bestätigt sind.
	 */
	vorschlaege?: KantenVorschlag[],
};

/**  A foreign lock as sent to the UI (serializable view of [`LockInfo`] plus the ready tooltip). */
export type ForeignLock = {
	path: string,
	owner: string,
	locked_at: string,
	tooltip: string,
};

/**
 *  A personenübergreifende Warnung (E19.1/E33): a colleague's frischer Stand is being co-tagged.
 *  Informational — carries no Härte. `None` ⇔ no foreign recent work to warn about.
 */
export type FremdWarnung = {
	/**  The colleague whose Stand is being co-tagged. */
	wer: string,
	/**  A ready human sentence („du taggst auch X' frischen Stand mit"). */
	satz: string,
};

/**  Exactly one outcome of the Import Gate. Serialised kebab-case for the UI. */
export type GateDecision = 
/**  Safe: clean, non-destructive import (Issue #3 path). Delegated to `import_folder`. */
"clean-init" | 
/**
 *  Dangerous but allowed: heavy binaries sit in history of a fresh/unshared repo, so a
 *  `git lfs migrate` history rewrite is offered — only behind the "Historie anfassen" gate.
 */
"migrate-behind-gate" | 
/**  Forbidden: the repo is shared, so rewriting history would poison others' clones (E38). */
"refuse";

/**
 *  What the Import Gate decided for a folder, plus the facts it decided on, for the UI to
 *  explain the stakes before any history is touched.
 */
export type GateReport = {
	/**  The one decision: clean-init | migrate-behind-gate | refuse. */
	decision: GateDecision,
	/**  Whether the folder already carries git history. */
	has_history: boolean,
	/**  Whether shared clones (a remote) exist — the refuse trigger (E38). */
	shared_clones_exist: boolean,
	/**  Whether heavy binaries are already committed into history. */
	giant_binaries_in_history: boolean,
};

/**
 *  The single verdict the Freigabe-Gate core returns for a checkpoint. Exactly one; total. It
 *  carries the **härte-sortierte Liste** (härtestes zuerst), the resulting **Knopf-Zustand**, and
 *  the optional personenübergreifende Warnung — so the UI renders the whole gate without
 *  re-deciding anything.
 */
export type GateVerdict = {
	/**
	 *  The open points, **härtestes zuerst** (Hart, then Weich, then Warnung), stable within a
	 *  Härte (input order preserved). Empty ⇔ alles sauber.
	 */
	punkte: OffenerPunkt[],
	/**  The resulting state of the one context-dependent button. */
	knopf: KnopfZustand,
	/**
	 *  `true` iff a harter Block is present — the button is off and only acting on the Aufgabe
	 *  dismisses it (mirrors `knopf == GesperrtDurchAufgabe`, kept explicit for the UI).
	 */
	harter_block: boolean,
	/**
	 *  `true` iff a weicher Block is present and no harter — i.e. a protokollierter Satz is
	 *  required to proceed (mirrors `knopf == TrotzdemFreigeben`).
	 */
	begruendung_noetig: boolean,
	/**  The personenübergreifende Warnung, if a colleague's frischer Stand is being co-tagged. */
	fremd_warnung: FremdWarnung | null,
};

/**
 *  Das Ergebnis von „Als Ordner öffnen": der materialisierte Pfad (Vorwärts-Schrägstriche), den die
 *  UI dem OS zum Öffnen übergibt, plus ob er neu angelegt oder schon vorhanden war.
 */
export type GeoeffneterOrdner = {
	/**  Absoluter Pfad des materialisierten Ordners, in Vorwärts-Schrägstrich-Anzeige. */
	pfad: string,
	/**  `true`, wenn der Ordner für diesen Stand neu angelegt wurde; `false`, wenn er schon stand. */
	neu: boolean,
};

/**
 *  The Härte of a single open point at the Freigabe-Gate (E19). Ordered **härtestes zuerst**:
 *  the `Ord` derive ranks `Hart < Weich < Warnung`, so a plain ascending sort puts the hardest
 *  items at the top of the list — exactly the „nach Härte sortierte Liste" of E19.3.
 */
export type Haerte = 
/**  Harter Block: an open blocking Aufgabe. Button off; only the task itself dismisses it. */
"hart" | 
/**  Weicher Block: a Waise / missing Pflicht-Artefakt. Overridable by a logged Begründung. */
"weich" | 
/**  Warnung: a Stale-Kante. Visible, never blocks, no Begründung. */
"warnung";

/**
 *  Herkunfts-Stempel einer kopierten Baustein-Definition: aus welchem Bibliotheks-Baustein
 *  (`from`) und in welcher `version` sie kopiert wurde. Nur Anzeige; kein Live-Link (ADR 0003).
 */
export type Herkunft = {
	/**  Bibliotheks-`id`, aus der kopiert wurde. */
	from: string,
	/**  Version zum Zeitpunkt des Kopierens. */
	version: number,
};

/**
 *  Which of a product's three searched sources a hit came from. Lets the UI label a hit and
 *  lets ranking prefer the most meaningful source.
 */
export type HitField = 
/**  A file name / path under the product matched. */
"dateiname" | 
/**  A line in the product's `_plm` metadata store matched. */
"plm" | 
/**  A line in `VERSION_NOTES.md` matched. */
"version-notes";

/**  Outcome of an import, returned to the UI shell. */
export type ImportResult = {
	/**  Whether this run ran `git init` (true) or found an existing repo and left it as-is (false). */
	git_initialized: boolean,
	/**  Number of leaf files marked `lockable` in `.gitattributes`. */
	locked_count: number,
	/**  The read-only projection of the freshly imported product (what the shell renders). */
	product: ProductView,
};

/**
 *  Eine Referenz auf das angelegte Issue, wie sie ans Frontend geht (für die „angelegt"-Bestätigung
 *  mit Link). **Kein** Token, keine Server-Interna.
 */
export type IssueRef = {
	/**  Die Issue-Nummer im Repo (`#<number>`). */
	number: number,
	/**  Die Web-URL des Issues, zum Öffnen im Browser. */
	html_url: string,
};

/**
 *  Woher eine Kante stammt — die drei Herkunftsstufen aus E20/Glossar (Issue #56). Reine Anzeige-
 *  und Pflege-Information; sie ändert **nichts** an der Stale-Logik (E26 vergleicht nur Zeitstempel).
 *  Sie erlaubt aber, Default-Kanten beim Stilllegen still in Ruhe zu schicken (E17) und in der UI
 *  Hand- von Automatik-Kanten zu unterscheiden.
 */
export type KantenHerkunft = 
/**  Von Hand gezogen (das echt Idiosynkratische) — der Default, auch für Altbestand ohne Feld. */
"hand" | 
/**  Baustein-Default: Kante **innerhalb** eines Bausteins (Gerber ← Layout), beim Onboarding angelegt. */
"baustein-default" | 
/**  Baustein-Paar-Default: über zwei bekannt zusammengehörige Bausteine, per Klick bestätigt. */
"paar-default";

/**
 *  Ein **deterministischer Kanten-Vorschlag** aus einer Paar-Default-Regel (E20). Wird in der UI
 *  angezeigt und **per Klick** zu einer echten [`Edge`] (Herkunft `PaarDefault`) bestätigt — nie
 *  automatisch angelegt.
 */
export type KantenVorschlag = {
	/**  Das abgeleitete Artefakt (Ordner-Pfad). */
	derived: string,
	/**  Die vorgeschlagene Quelle (Ordner-Pfad). */
	source: string,
	/**  `id` des Bausteins, dessen Paar-Regel den Vorschlag trägt (Anzeige). */
	baustein_id: string,
	/**  `id` des Partner-Bausteins, der den Vorschlag mit auslöst (Anzeige). */
	partner_id: string,
};

/**
 *  Die **abgeleitete Karten-Projektion** (#53): der gefaltete Git-Status **plus** das
 *  orthogonale Stale-Flag. Das ist die Form, die #55 (Filter) und #56 (Kanten) konsumieren —
 *  stabil und vollständig getrennt: `status` aus Git, `stale` aus Kanten.
 */
export type KartenProjektion = {
	/**  Der live aus Git abgeleitete Karten-Status (E26). */
	status: KartenStatus,
	/**
	 *  **Stale** (E26/E40): es existiert eine Hand-Kante **und** eine Quelle ist neuer als die
	 *  Ableitung. `false`, wo keine Kante zeigt — keine Kante = keine Warnung. Orthogonal zum
	 *  `status`: eine ruhige „vorhandene" Karte kann trotzdem stale sein.
	 */
	stale: boolean,
};

/**
 *  Der **abgeleitete Karten-Status** einer Artefakt-Karte (E26). Serialisiert in kebab-case zur
 *  UI (`"vorhanden"`/`"geaendert"`/`"fehlt"`/`"uebernommen"`/`"ignoriert"`). Das orthogonale
 *  **Stale**-Flag ([`KartenProjektion::stale`]) reitet daneben, nicht hier hinein — eine Karte
 *  kann „vorhanden" **und** „stale" sein (Quelle neuer als Ableitung, E26/E40).
 */
export type KartenStatus = 
/**  Alle Dateien erfasst und ruhig — der Normalfall. Auch die Antwort für eine leere Karte. */
"vorhanden" | 
/**  Mindestens eine Datei ist im Arbeitsbereich geändert — der laute „prüf-mich"-Fall. */
"geaendert" | 
/**  Mindestens eine erfasste Datei ist verschwunden (deleted). */
"fehlt" | 
/**  Frisch hinzugekommene Dateien, sonst nichts Lauteres. */
"uebernommen" | 
/**  Die ganze Karte ist ignoriert (alle Dateien `!!`) — der stumme Außenfall. */
"ignoriert";

/**  The three Zustände of the *one* context-dependent button (E19.3). Exactly one; total. */
export type KnopfZustand = 
/**  Alles sauber (or only Warnungen) → the button is the plain „Taggen". Proceeds freely. */
"taggen" | 
/**  A weicher Block (and no harter) → „Trotzdem freigeben"; a protokollierter Satz is required. */
"trotzdem-freigeben" | 
/**
 *  A harter Block → the button is **aus** (gesperrt). The Ausweg is a click on the Aufgabe;
 *  no Begründung dismisses it.
 */
"gesperrt-durch-aufgabe";

/**
 *  Was das Frontend über das Konto sieht: die normalisierte Base-URL und der angemeldete Account —
 *  **nie** der Token. Ein fehlendes Konto ist `None`-felder-frei: dann wird gar kein [`KontoView`]
 *  geliefert (das Command gibt `Option<KontoView>` zurück).
 */
export type KontoView = {
	/**  Die normalisierte Server-Base-URL `scheme://host[:port]`. */
	base_url: string,
	/**  Der angemeldete Account-Name (aus `GET /api/v1/user`, beim Speichern bestätigt). */
	account: string,
};

/**
 *  Ein Etikett, wie es der Etiketten-Picker im Formular zeigt (Issue #85): Id (zum Anhängen), Name
 *  und Farbe (Hex **ohne** führendes `#`, wie Forgejo/Gitea sie liefert — das Frontend setzt das
 *  `#` zum Rendern davor). Kein Token, keine Server-Interna.
 */
export type Label = {
	id: number,
	name: string,
	color: string,
};

/**
 *  The domain-language question shown in the single orange-frame loud exception. It names the
 *  contested artifact in the tool's own words and offers the two stands to choose from. It holds
 *  **no** git conflict marker by construction (see [`LoudQuestion::contains_git_marker`]).
 */
export type LoudQuestion = {
	/**
	 *  The one-line question, e.g. „dein und Bens Gehäuse-Stand widersprechen sich — welcher
	 *  gilt?". Domain language only.
	 */
	frage: string,
	/**
	 *  The contested artifact's product-relative paths, named as artifacts (never as git refs).
	 *  At least one; these are exactly the unmergeable diverged paths.
	 */
	artefakte: string[],
	/**  The two stands to choose between, each with its domain label. */
	optionen: StandOption[],
};

/**
 *  Was die Öffnen-Aktion einer Artefakt-Karte tun soll, wenn der Nutzer sie anklickt.
 *  `Auto` heißt: dominante Einzeldatei → diese öffnen, sonst den Ordner öffnen (PRD §14).
 */
export type Oeffnen = 
/**  Hauptdatei wenn es eine dominante gibt, sonst Ordner (PRD §14). Default. */
"auto" | 
/**  Immer die Hauptdatei im OS-Standardprogramm öffnen. */
"datei" | 
/**  Immer den Heimat-Ordner öffnen. */
"ordner";

/**
 *  One open point in the härte-sortierte Liste. Carries everything the UI needs to render the
 *  row *and* its Auswege without re-deciding: its Härte, its kind, a stable `ref_id` (the task
 *  id, the orphan path, the missing artefact label, or the stale derivation path) and a human
 *  `label`. A hard task additionally carries its three Auswege via `ref_id` (the UI acts on the
 *  task by that id).
 */
export type OffenerPunkt = {
	/**  The Härte of this point — drives both the sort and the row's visual weight. */
	haerte: Haerte,
	/**  What kind of point this is (the source axis behind the Härte). */
	art: Punktart,
	/**
	 *  A stable reference: task id for an Aufgabe, product-relative path for a Waise/Stale-Kante,
	 *  the Pflicht label for a missing artefact. The UI keys rows and Auswege on this.
	 */
	ref_id: string,
	/**  A human one-liner naming the point (the task title, the orphan filename, …). */
	label: string,
};

/**  One registered product that could not be searched, with a short honest reason. */
export type OfflineProduct = {
	product_path: string,
	product_name: string,
	/**  Human German reason, e.g. "Ordner nicht erreichbar". */
	reason: string,
};

/**
 *  Eine **Baustein-Paar-Default-Kante** (E20): „wenn dieser Baustein **und** der Partner-Baustein
 *  `partner_id` beide im Stack sind, schlage die Kante `derived_glob` ← `source_glob` vor". Der
 *  `derived_glob`/`source_glob` greift über die Heimaten **beider** Bausteine hinweg (das ist der
 *  Sinn der Paar-Stufe: die Kante überspannt zwei Bausteine und hat auf Baustein-Ebene keine
 *  Heimat). Rein deterministisch — **kein** ML, keine Daten, kein Parser (E21). Der Vorschlag wird
 *  **per Klick bestätigt**, nie automatisch angelegt (Onboarding bleibt ruhig).
 */
export type PaarDefaultKante = {
	/**  `id` des Partner-Bausteins, der zusätzlich im Stack liegen muss, damit der Vorschlag greift. */
	partner_id: string,
	/**  Glob des abgeleiteten Artefakts (z.B. Pick-and-Place). */
	derived_glob: string,
	/**  Glob der Quelle, aus der es stammt (z.B. Layout **und** BOM — je eine Paar-Kante). */
	source_glob: string,
};

/**
 *  Die abgeleitete **primäre Aktion** einer Artefakt-Karte (PRD §14). `Auto` löst sich aus dem
 *  Bestand auf: gibt es eine **dominante Einzeldatei** (die Hauptdatei ist eindeutig — nur sie
 *  trifft die höchste Priorität), wird die Datei geöffnet, sonst der Ordner. Eine ausdrückliche
 *  Baustein-Wahl (`Datei`/`Ordner`) bleibt. Rein und total — dieselbe Tabelle wie
 *  `Baustein::resolve_oeffnen`, hier aber an die abgeleitete Dominanz gekoppelt.
 */
export type PrimaerAktion = 
/**  Die Hauptdatei im OS-Standardprogramm öffnen. */
"datei" | 
/**  Den Heimat-/Artefakt-Ordner im Dateimanager öffnen. */
"ordner";

/**  Read-only projection of a product folder. */
export type ProductView = {
	name: string,
	branch: string,
	version: string,
	bausteine: ProduktBaustein[],
};

/**  A leaf folder understood as a building block of the product. */
export type ProduktBaustein = {
	/**  Folder name; the UI renders this as a caps label. */
	name: string,
	/**  Folder path relative to the product root (muted Mono in the UI). */
	path: string,
	/**  Representative file of this Baustein, relative to the product root, if any. */
	main_file: string | null,
};

/**
 *  Der Produkt-Stack: die kopierten Bausteine eines Produkts. Vollständig selbsttragend; das
 *  Produkt funktioniert auch ohne Bibliothek (ADR 0003).
 */
export type ProduktStack = ProduktStack_Serialize | ProduktStack_Deserialize;

/**
 *  Der Produkt-Stack: die kopierten Bausteine eines Produkts. Vollständig selbsttragend; das
 *  Produkt funktioniert auch ohne Bibliothek (ADR 0003).
 */
export type ProduktStack_Deserialize = {
	/**  Optionaler Herkunfts-Name des gewählten Toolstacks (Anzeige). */
	toolstack?: string | null,
	/**  Die kopierten Bausteine (Vollkopie je + Stempel). */
	bausteine: StackBaustein[],
};

/**
 *  Der Produkt-Stack: die kopierten Bausteine eines Produkts. Vollständig selbsttragend; das
 *  Produkt funktioniert auch ohne Bibliothek (ADR 0003).
 */
export type ProduktStack_Serialize = {
	/**  Optionaler Herkunfts-Name des gewählten Toolstacks (Anzeige). */
	toolstack?: string | null,
	/**  Die kopierten Bausteine (Vollkopie je + Stempel). */
	bausteine: StackBaustein[],
};

/**
 *  The outcome of a publish attempt (Issue #44). Parallels [`crate::syncglue::SyncOutcome`]: most of
 *  the time the product publishes and the ceremony advances; but if the chosen Server-Repo already
 *  carries Stände that contradict the local product on an **unmergeable** artifact, publishing
 *  **stops** and raises the single domain-language exception instead of letting git reject the push.
 */
export type PublishOutcome = 
/**  The product was published; the refreshed ceremony state (now `eingerichtet`) rides along. */
{
	kind: "published",
} & SetupReport | 
/**
 *  Integrating the non-empty Server-Repo hit a real contradiction on an unmergeable artifact.
 *  The push was **not** performed; the user answers the loud question (via the same
 *  `resolve_sync` as the daily sync), then re-publishes — the re-push is then a clean
 *  fast-forward. Carries the domain-language question; never a git marker.
 */
{
	kind: "laute-ausnahme",
} & LoudQuestion;

/**
 *  What kind of open point an item is — the source axis behind its [`Haerte`]. Kept distinct from
 *  the Härte so the UI can render the right Auswege (a hard task gets Erledigen/Verwerfen/…; a
 *  Waise gets nothing but the Begründung path).
 */
export type Punktart = 
/**  An open blocking Aufgabe (→ harter Block). */
"aufgabe" | 
/**  A Waise — a tracked file without an Etikett (→ weicher Block). */
"waise" | 
/**  A missing Pflicht-Artefakt (→ weicher Block). */
"fehlende-pflicht" | 
/**  A Stale-Kante: the derivation is older than its source (→ Warnung). */
"stale-kante";

/**
 *  One registered product: **only its path** (forward-or-native as the OS gave it) plus the
 *  folder name as a convenience label the UI can show without re-reading the disk. The label is
 *  derived from the path, never an independent fact — so it cannot drift from the real folder.
 */
export type RegisteredProduct = {
	/**  Absolute path to the product folder. The single source of truth for this entry. */
	path: string,
	/**  Folder name, derived from `path` — a display convenience, not a second fact. */
	name: string,
};

/**
 *  The **Art** (kind) of a Revision (E42). The block-strictness is a property of the
 *  revision act, not of the branch. A freshly promoted Revision is a **Prototyp**
 *  (lax: warnings only, frictionless tagging); a deliberate **Toggle** raises it to a
 *  **Freigabe** (streng), which write-protects the tag (E8). Toggling back is a deliberate
 *  reversible „Un-Release" (E22). Serialized to the UI in kebab-case (`"prototyp"` /
 *  `"freigabe"`).
 */
export type RevisionArt = 
/**  Lax: the default for a new Revision. No write-protect, warnings only. */
"prototyp" | 
/**
 *  Streng: a released Revision. Its tag is write-protected; reaching it is the
 *  deliberate Freigabe toggle.
 */
"freigabe";

/**
 *  One match inside one product. Carries enough context for the UI to show *where* without a
 *  second round-trip: the product, the field, the relative file the hit lives in, and the
 *  matched text (a file path, or the matched line for content hits).
 */
export type SearchHit = {
	/**  Absolute path of the product this hit belongs to. */
	product_path: string,
	/**  Display name of the product (folder name). */
	product_name: string,
	/**  Which source matched. */
	field: HitField,
	/**  Product-relative file the hit was found in (forward slashes). */
	file: string,
	/**  The matched text: a relative file path for `Dateiname`, the matched line for content. */
	text: string,
	/**  Computed relevance; higher sorts first. Stable, derived purely from the hit. */
	score: number,
};

/**
 *  The full result of one fan-out search. Reachable hits plus the honest offline tally, so the
 *  UI can render results AND "N von M offline, nicht durchsucht" from one payload.
 */
export type SearchResult = {
	/**  All hits across all reachable products, already merged + ranked (best first). */
	hits: SearchHit[],
	/**  Registered products that could not be opened — reported, never silently dropped. */
	offline: OfflineProduct[],
	/**  How many registered products were searched (reachable). */
	searched: number,
	/**  Total registered products considered (`searched + offline.len()`). */
	total: number,
};

/**
 *  What the UI renders for the ceremony: the stage, the facts behind it, and — once a remote is
 *  configured — the credential-free clone URL to hand a colleague (the invite).
 */
export type SetupReport = {
	/**  The pure stage decision (drives whether the ceremony or the settled readout shows). */
	stage: SetupStage,
	/**  Whether a remote named [`REMOTE_NAME`] is configured. */
	has_remote: boolean,
	/**  Whether the product has been published (an upstream exists). */
	has_published: boolean,
	/**  The credential-free clone URL a colleague uses, if a remote is configured (the invite). */
	clone_url: string | null,
};

/**
 *  Where a product stands in the ceremony. Serialised kebab-case for the UI, which shows the
 *  ceremony **only** in `NotConfigured` and a settled "eingerichtet" readout otherwise — so the
 *  one-time flow is clearly separated from daily use (E41).
 */
export type SetupStage = 
/**  No remote configured: offer the one-time ceremony. */
"not-configured" | 
/**  A remote is configured but nothing has been published yet: offer the first publish. */
"remote-set-not-published" | 
/**  Remote configured and the product has been published: settled. Ceremony is done. */
"eingerichtet";

/**  Eine Baustein-Vollkopie im Produkt-Stack: die ganze Definition **plus** Herkunfts-Stempel. */
export type StackBaustein = {
	/**  Herkunfts-Stempel (Anzeige/„Update verfügbar"); kein Live-Link. */
	herkunft: Herkunft,
} & Baustein;

/**
 *  A fired Stale-Warnung: the derivation along the edge it sits on is older than its source.
 *  Serialized straight to the UI, which paints the derived card as „needs attention".
 */
export type StaleWarning = {
	/**  The stale derivation (the artifact to re-check). */
	derived: string,
	/**  The source that moved on without it. */
	source: string,
	/**  Source timestamp (newer). */
	source_timestamp: string,
	/**  Derivation timestamp (older). */
	derived_timestamp: string,
};

/**
 *  Which stand the user must choose between in a loud exception. The whole question is framed in
 *  domain language; this enum never leaks a git ref or marker.
 */
export type StandChoice = 
/**  Keep my local stand for the contested artifact. */
"mine" | 
/**  Take the colleague's stand for the contested artifact. */
"theirs";

/**
 *  A single node in the version tree: a Stand, possibly promoted to a Revision and/or
 *  with its binary content offloaded. Serialized straight to the UI.
 */
export type StandNode = {
	/**  Stable id (commit hash). The UI keys rows on this; never displayed as git. */
	id: string,
	/**  Machine timestamp `YYYY-MM-DDTHH:MM:SSZ`. */
	timestamp: string,
	/**
	 *  Product-relative path the auto-commit recorded, parsed from the boring message;
	 *  `"."` when the message is not the auto shape (e.g. a Revision/import commit).
	 */
	path: string,
	/**  Set when this Stand has been promoted to a Revision: its human version label. */
	revision: string | null,
	/**
	 *  The Revision-Art (Prototyp/Freigabe — E42), present only when `revision` is set.
	 *  A Freigabe write-protects the tag; a Prototyp is lax. `None` for a plain Stand.
	 */
	revision_art: RevisionArt | null,
	/**  Whether a `VERSION_NOTES.md` text exists for this Revision (only if `revision`). */
	has_notes: boolean,
	/**
	 *  Whether this node's binary content has been offloaded (E36). The node stays in the
	 *  tree, honestly marked "Inhalt ausgelagert".
	 */
	offloaded: boolean,
	/**
	 *  Whether this Stand has reached the **shared** line — it is on `origin/<shared>` as far as
	 *  this machine knows (E47, #30). The Versionsbaum marks it „veröffentlicht". Distinct from a
	 *  Freigabe-Art: a Prototyp Stand riding on the published line is veröffentlicht, not freigegeben.
	 */
	veroeffentlicht: boolean,
	/**
	 *  Which **Bahn** (lane) this Stand sits on: `0` is the trunk (the active line), each
	 *  diverging Zweig gets its own positive index. A single linear history is all lane `0`.
	 */
	lane: number,
	/**
	 *  The Zweig name labelling this Stand's lane (e.g. `gehaeuse-v2`). `None` for the trunk
	 *  (lane 0) and for unnamed lines; the UI shows it once per lane (at the lane's tip).
	 */
	branch: string | null,
	/**
	 *  `true` when this Stand lies on the active line (the user's current Zweig). The active
	 *  line stays clearly marked even when other Zweige are visible.
	 */
	on_active: boolean,
	/**
	 *  The Stände this one **folgt auf** (its direct predecessors): one for a normal Stand,
	 *  two where two Linien were **zusammengeführt**. The UI draws a connector from this Stand
	 *  down to each predecessor present in the tree, so forks and Zusammenführungen become
	 *  visible lines. Ids only — never shown as git.
	 */
	parents: string[],
};

/**  One choosable stand in the loud question, with a domain label. No git wording. */
export type StandOption = {
	choice: StandChoice,
	/**  The label, e.g. "mein Stand" / "Bens Stand". Domain language. */
	label: string,
};

/**  Eine Startaufgabe, die beim Onboarding eines Bausteins in einem Produkt angelegt wird. */
export type Startaufgabe = {
	/**  Menschlicher Titel der Aufgabe/des Hinweises. */
	titel: string,
	/**  Aufgabe (verpflichtend) oder Hinweis (nie blockierend). */
	typ: AufgabenTyp,
	/**  Ob diese Aufgabe das Freigabe-Gate hart blockiert. Für `Hinweis` immer `false`. */
	blockiert?: boolean,
};

/**
 *  Die Antwort des Stilllegens (Issue #51): die label-only-**Wirkung** (welche Globs erlöschen,
 *  welche Dateien zu Waisen werden, welches Sediment liegen bleibt) **plus** die frisch berechnete
 *  Werkbank, sodass die UI die neuen Waisen im Unzugeordnet-Fach sofort sieht.
 */
export type StilllegenResult = StilllegenResult_Serialize | StilllegenResult_Deserialize;

/**
 *  Die Antwort des Stilllegens (Issue #51): die label-only-**Wirkung** (welche Globs erlöschen,
 *  welche Dateien zu Waisen werden, welches Sediment liegen bleibt) **plus** die frisch berechnete
 *  Werkbank, sodass die UI die neuen Waisen im Unzugeordnet-Fach sofort sieht.
 */
export type StilllegenResult_Deserialize = {
	wirkung: StilllegenWirkung,
	stack: ProduktStack_Deserialize,
	werkbank: WerkbankView,
};

/**
 *  Die Antwort des Stilllegens (Issue #51): die label-only-**Wirkung** (welche Globs erlöschen,
 *  welche Dateien zu Waisen werden, welches Sediment liegen bleibt) **plus** die frisch berechnete
 *  Werkbank, sodass die UI die neuen Waisen im Unzugeordnet-Fach sofort sieht.
 */
export type StilllegenResult_Serialize = {
	wirkung: StilllegenWirkung,
	stack: ProduktStack_Serialize,
	werkbank: WerkbankView,
};

/**
 *  Die **Wirkung** eines Stilllegens, rein berechnet aus Stack + erfassten Dateien (kein I/O).
 *  Das ist die Antwort der tiefen Sub-Funktion: *Was passiert, wenn ich diesen Baustein stilllege?*
 */
export type StilllegenWirkung = {
	/**  Die Globs des Bausteins, die mit dem Stilllegen **erlöschen** (nicht mehr greifen). */
	erloschene_globs: string[],
	/**
	 *  Die zuvor vom Baustein getragenen Dateien, die durch das Stilllegen zu **Waisen** werden
	 *  (produkt-relativ, Vorwärts-Slashes, sortiert). Sie wandern ins Unzugeordnet-Fach — nichts
	 *  wird verschoben/gelöscht.
	 */
	neue_waisen: string[],
	/**
	 *  Die Ignore-/LFS-Muster des Bausteins, die als **Sediment** in den Dotfiles liegen bleiben
	 *  (nie automatisch entfernt). Reine Diagnose/Anzeige — die Dotfiles selbst bleiben unberührt.
	 */
	sediment: string[],
	/**
	 *  Invariante: Stilllegen ist label-only — **nichts wird verschoben oder gelöscht**. Immer `true`
	 *  (explizit getragen, damit die Akzeptanz „nichts relocated/removed" prüfbar im Vertrag steht).
	 */
	nichts_bewegt: boolean,
};

/**  The outcome of one silent daily sync pass, ready for the UI in the tool's vocabulary. */
export type SyncOutcome = {
	status: SyncStatus,
};

/**
 *  The quiet daily sync state shown to the user, in the tool's OWN vocabulary (E41). Never
 *  push/pull/merge. This is what the calm status readout reflects after a silent sync; a loud
 *  exception is carried separately as the [`SyncDecision`].
 */
export type SyncStatus = 
/**  Local and remote agree — "aktuell". Nothing to do, nothing shown. */
"aktuell" | 
/**  A silent merge brought the colleague's free changes in — still "aktuell", quietly. */
"gesichert" | 
/**
 *  The stiller Sync stopped on a real contradiction (E41): the single loud exception. Carries
 *  the domain-language question the UI raises in its one orange-frame moment.
 */
{ "laute-ausnahme": LoudQuestion };

/**
 *  One Aufgabe or Hinweis. The minimal model (US 28): `title` / `status` / `kind` / `link` /
 *  `due` + the `blocks_everywhere` opt-out (US 30). `id` is a stable opaque key the store
 *  assigns; `created_at` is an injected timestamp (the core never reads the clock).
 */
export type Task = {
	/**  Stable opaque id (the store assigns it; the UI keys rows on it). */
	id: string,
	/**  Titel — the one piece of free human text. */
	title: string,
	/**  Typ: distinguishes Aufgabe (block-capable) from Hinweis (never blocks) — and *only* that. */
	kind: TaskKind,
	/**  Status: offen / erledigt / verworfen. */
	status: TaskStatus,
	/**  Optional Verknüpfung to Produkt/Version/Arbeitsbereich/Artefakt. `None` = free-floating. */
	link?: TaskLink | null,
	/**
	 *  Optional Fälligkeit as a date string `YYYY-MM-DD` (lexicographically orderable). `None` =
	 *  kein Termin.
	 */
	due?: string | null,
	/**
	 *  „blockiert überall" opt-out (US 30): when set on an Aufgabe, it is meant to block
	 *  **kontextunabhängig**. Ignored for a Hinweis (a Hinweis never blocks). The block decision
	 *  itself is Issue #49; this is only the flag.
	 */
	blocks_everywhere?: boolean,
	/**  Injected creation timestamp `YYYY-MM-DDTHH:MM:SSZ` (the core never reads a clock). */
	created_at: string,
};

/**
 *  What an item *can* do at a checkpoint. The **only** thing that distinguishes the two kinds
 *  (US 27): an [`Aufgabe`](TaskKind::Aufgabe) is block-*capable*, a [`Hinweis`](TaskKind::Hinweis)
 *  never blocks. The block *decision* itself is out of scope here (Issue #49); this core only
 *  records the capability so the Freigabe-Gate can later read it.
 */
export type TaskKind = 
/**  Verpflichtend — *kann* blockieren (am Freigabe-Revision, abhängig vom Kontext, E42). */
"aufgabe" | 
/**  Blockiert nie — eine reine Notiz/Erinnerung. */
"hinweis";

/**
 *  The optional Verknüpfung (US 28): an item can hang off the Produkt, a Version, an
 *  Arbeitsbereich, or a single Artefakt — or off nothing at all (a free-floating item is
 *  valid; the list stays schlank). Tagged so the on-disk JSON and the frontend mirror stay
 *  honest and round-trip exactly.
 */
export type TaskLink = 
/**  The product as a whole. */
{ kind: "produkt" } | 
/**  A specific Version/Revision, by its human label or Stand id. */
{ kind: "version"; ref: string } | 
/**  An Arbeitsbereich, by its product-relative path. */
{ kind: "arbeitsbereich"; ref: string } | 
/**  A single Artefakt, by its product-relative path. */
{ kind: "artefakt"; ref: string };

/**
 *  The lifecycle status of a task. Deliberately tiny (no Kanban columns, US 28): an item is
 *  open until it is either done or dropped. Only `Offen` items can ever block.
 */
export type TaskStatus = 
/**  Noch offen — the only status that can carry a block. */
"offen" | 
/**  Erledigt. */
"erledigt" | 
/**  Verworfen (bewusst herabgestuft/gestrichen). */
"verworfen";

/**
 *  Ein **Toolstack**: eine benannte, geordnete Auswahl von Baustein-`id`s aus der Bibliothek
 *  (ADR 0003). Repräsentiert einen Standard-Toolstack, aus dem ein Produkt-Stack kopiert wird.
 */
export type Toolstack = {
	/**  Stabile Kebab-Identität, z.B. `"standard-hw"`. */
	id: string,
	/**  Menschlicher Name, z.B. `"Standard Hardware"`. */
	name: string,
	/**  Referenzierte Baustein-`id`s in Reihenfolge. */
	baustein_ids: string[],
};

/**
 *  Ein **Unzugeordnet-Fach pro Arbeitsbereich**: die Waisen eines Arbeitsbereichs (oberster
 *  Ordner). Eine Waise ist eine erfasste Datei ohne Etikett — nichts geht verloren, der Ordner
 *  bleibt als Zuordnungs-Hinweis.
 */
export type UnzugeordnetFach = {
	/**  Der Arbeitsbereich (oberster Ordnername; `""` = Produktwurzel). */
	arbeitsbereich: string,
	/**  Die Waisen-Dateien, produkt-relativ, sortiert. */
	dateien: string[],
};

/**
 *  The dark "display" version tree the UI renders, plus the active revision version that
 *  the version bar shows in Mono.
 */
export type VersionGraph = {
	/**  Stände newest-first. */
	nodes: StandNode[],
	/**
	 *  The active Revision version (newest promoted Stand), or `None` if the product has
	 *  no Revision yet. The version bar shows this in Mono.
	 */
	active_revision: string | null,
	/**
	 *  The Art of the active Revision (Prototyp/Freigabe — E42), or `None` if there is no
	 *  active Revision. The version bar shows the Freigabe/Prototyp state alongside it.
	 */
	active_revision_art: RevisionArt | null,
	/**  Archive label for offloaded nodes, surfaced once for the legend; `None` if none. */
	offloaded_archive: string | null,
	/**  Name of the active line (Zweig), echoed for the UI marker; `None` if unknown. */
	active_branch: string | null,
	/**
	 *  Number of distinct lanes in the tree; `1` for a single linear history. The UI uses
	 *  it to size the lane gutter only when there is more than one line.
	 */
	lane_count: number,
};

/**
 *  Exactly one action the Lock Warden returns per snapshot. The glue in [`crate::pushglue`] is
 *  the only thing that turns one of these into git/LFS calls.
 */
export type WardenAction = 
/**
 *  **Freigabe-Push** — publish the finished binary to the shared `main` stand AND release the
 *  lock atomically. The *only* action that publishes a binary to shared `main` / the LFS
 *  store (E35/E36). Reachable only at a Revision and only when the lock is being released.
 */
"freigabe-push" | 
/**
 *  **Sicherungs-Push** — mirror local intermediate commits to the personal backup
 *  namespace. Private backup; does **not** publish to shared `main`, does **not** unlock.
 */
"sicherungs-push" | 
/**
 *  **Auto-Unlock** — release a held-by-me lock whose path is locally clean (E31/E35 self-
 *  healing). Fires at every checkpoint iff clean; never otherwise.
 */
"auto-unlock" | 
/**
 *  **Refuse** — do nothing: nothing to do, or not ours to touch (a foreign lock). The safe
 *  default that can never break the invariant.
 */
"refuse";

/**  Die ganze Werkbank-Sicht eines Produkts: Karten + Unzugeordnet-Fächer. */
export type WerkbankView = {
	/**  Artefakt-Karten, sortiert nach `artefakt_id`. */
	karten: ArtefaktKarte[],
	/**  Unzugeordnet-Fächer, eines je Arbeitsbereich mit Waisen, sortiert nach `arbeitsbereich`. */
	unzugeordnet: UnzugeordnetFach[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

